# Personal aliases
alias EDIT_BASHRC='nano /.bashrc'
alias edit_alias='nano /.bash_aliases'

# built-in commands
alias ll='ls -alF --color=auto'
alias rm='rm -I'

## gcc and debugging
alias gc='gcc -ansi -pedantic-errors -Wall -Wextra -DNDEBUG -o3'
alias gc9='gcc -std=c99 -pedantic-errors -Wall -Wextra -DNDEBUG -o3'
alias gd='gcc -ansi -pedantic-errors -Wall -Wextra -g'
alias gd9='gcc -std=c99 -pedantic-errors -Wall -Wextra -g'
alias gdo='gcc -ansi -pedantic-errors -Wall -Wextra -g -c'
alias vlg='valgrind --leak-check=yes --track-origins=yes'

## Nano
alias nano='nano -m -q -l --minibar'
alias sudo_nano='sudo nano -m -q -l --minibar'

# dnf
alias update='sudo dnf upgrade --refresh -y'
alias sdi='sudo dnf install'

#ssh connection
alias thinkpad='ssh matan@192.168.1.110'

# other
alias rsync='rsync -avh --progress'


## apt
#alias sa='sudo apt'
#alias sai='sudo apt install'
#alias sau='sudo apt update && sudo apt upgrade -y'
#alias srm='sudo apt remove'
